### ISSUE TITLE
Extra unlabeled button when using navbarPage?

### ISSUE THREAD

**Issue by jsetlik-coursework** [daattali/shinyalert#13]
I hope this hasn't been covered, I did look through the issues and didn't see anything.

It seems that when using a navbarPage with shinyalert you get a half-sized, unlabeled button on the navbar.

Here's an example:

    library(shiny)
    library(shinyalert)

    ui <- navbarPage(
   
      "test",
       tabPanel("tab1",
          sidebarPanel(),
          mainPanel())
       #,useShinyalert()
      )

    server <- function(input, output) {}

    shinyApp(ui = ui, server = server)

if you uncomment the `useShinyalert()` then you should see the button:
![screenshot-127 0 0 1-6385-2018-03-07-12-15-58-379](https://user-images.githubusercontent.com/7795022/37110365-aee257f6-220a-11e8-8416-0e11633b8461.png)

**Comment by daattali** [comment]
That's because `navbarPage()` expects only tabs. You can't pass it `useShinyalert()`, that's not a tab. The solution is similar to the one for using `shinyjs::useShinyjs()`: https://deanattali.com/shinyjs/advanced#usage-navbarpage

**Comment by jsetlik-coursework** [comment]
Thanks Dean.  Sorry if that was the wrong place.
