### ISSUE TITLE
how to assing ID for shinyalert

### ISSUE THREAD

**Issue by jaspershen** [daattali/shinyalert#14]
Hi, dattali,
shinlyalert is a very good tool for shiny. However, I have a question about how to assign a specific ID for shinyalert, I saw in your readME, you said can "The return value of the modal can be accessed via input$shinyalert (or using a different input ID if you specify the inputId parameter) in the Shiny server’s code, as if it were a regular Shiny input.". however, there is no inputID or id parameter in the shinyalert function, so I don't know how to specify the ID for a shilyaler obejct?
Looking forward your reply.
Thank your very much.

**Comment by daattali** [comment]
The `inputId` parameter was added after the package was uploaded to CRAN (https://github.com/daattali/shinyalert/blob/master/NEWS.md#shinyalert-100) so you need to install the package using devtools::install_github() to get this feature
