### ISSUE TITLE
Possibility to customize dimensions of alert widgets

### ISSUE THREAD

**Issue by lbusett** [daattali/shinyalert#17]
Hi, 

   first of all, thanks for this package! Really useful and easier to use than shiny modals. 

I was just wondering if it is possible to somehow "customize" the appearence of the modal widgets, for example to change the dimensions of the icon or the font size of the messages. 

I already tried changing imageHeight / imageWidth, but with no avail. 

Thanks in advance, 

   Lorenzo

**Comment by daattali** [comment]
There is no builtin native way to customize the appearance, but you can use css to customize the appearance of any and every item. If you don't know css, you can take a couple hours to learn the basics using any online tutorial and that should probably be enough to get started

**Comment by lbusett** [comment]
Ok, thanks for the answer.  I'll have a look and see if I can manage using CSS. 

By the way: this would involve also using the `className` argument in `shinyalert` , right ? 

Lorenzo

**Comment by daattali** [comment]
It could, but doesn't have to. If you want different popups to look
differently, you could give them different classes. If all popups should
have the same look then it's not necessary

**Comment by KerrynHHH** [comment]
Hi there, 

I'm also looking to alter the font size, and it would be good to justify left, so no big alterations.

Can you expand on what you mean by _use css to customize_ - and where is a good place to learn to do this specific type of editing? It looks like the default css file for shinyalerts is not the bootstrap.css file in my www folder, but is the 'shinyalert.min.css' file:
<img width="228" alt="shinyalert css URL" src="https://user-images.githubusercontent.com/66767900/84351086-fabd3180-abfd-11ea-9d35-6e7b3f4e2f91.PNG">

I'm having trouble changing the source shown above, to have my code either refer to my local boostrap.css file containing some **shiny-alert** css code, or even a 'style.css' file in my local www folder as referred to here, https://rdrr.io/cran/shinyalert/src/inst/examples/demo/ui.R.
    _fluidPage(
        theme = "bootstrap_NOPD.css",
        includeCSS(file.path('www', 'style.css')),_

Please excuse my ignorance, I've looking around to solve this independently - but clearly I'm not using the right terms/search words, what should I be doing - or where should I be looking to skill up?

**Comment by daattali** [comment]
FYI, there will soon be a `size` parameter that will make this possible easily
