### ISSUE TITLE
demo application not loading

### ISSUE THREAD

**Issue by thercast** [daattali/shinyalert#18]
I just noticed today that your demo shiny application is not loading due to a 502 nginx error (see screenshot below).  Not a huge deal but wanted to make you aware of it.

![screen shot 2018-09-14 at 8 53 29 am](https://user-images.githubusercontent.com/1043111/45551383-bf5cbb80-b7fb-11e8-9243-ed8756eec9c0.png)

**Comment by daattali** [comment]
Thanks Eric! The entire server was down, this was good to know :)
