### ISSUE TITLE
Alert slow with callback and large memory reactive

### ISSUE THREAD

**Issue by dkulp2** [daattali/shinyalert#19]
If there is a reactive object that is very large then the shinyalert modal is very slow when there is an R callback. 

This is a very odd problem and I spent hours trying to create a minimal example. I find on both Linux and Windows that clicking the modal _with callback_ will take over ten seconds to display if the allocated matrix is over a GB. But the modal without the callback is fast regardless.

Here's sample code: https://gist.github.com/dkulp2/f1a773fcf29cfccd788bc7c8b7b35189

Let me know if I can help. This has become a problem with a production app and I'm eager to try to resolve it.

**Comment by daattali** [comment]
Thanks for the report and the great reprex, and for taking the time yourself to pinpoint when the problem happens. This has been fixed, please confirm on your end as well.
