### ISSUE TITLE
Error in Shinyalert: unused arguments

### ISSUE THREAD

**Issue by syzdekbr** [daattali/shinyalert#21]
Great package with shinyalert, but I'm getting errors using it now.  I recently updated R (3.6.1) and RStudio (1.2.1335).

library(shiny)
library(shinyalert)

ui <- fluidPage(
useShinyalert(), 
    sidebarLayout(
        sidebarPanel(
        actionButton("test", "Test This")
        ),
        mainPanel(
        )
    )
)

server <- function(input, output) {

    observeEvent(input$test,{
        shinyalert(
            title = "Hello",
            text = "This is a modal",
            closeOnEsc = TRUE,
            closeOnClickOutside = FALSE,
            html = FALSE,
            type = "success",
            showConfirmButton = TRUE,
            showCancelButton = FALSE,
            confirmButtonText = "OK",
            confirmButtonCol = "#AEDEF4",
            timer = 0,
            imageUrl = "",
            animation = TRUE
        )
    })
}

# Run the application 
shinyApp(ui = ui, server = server)

Error is: Warning: Error in shinyalert: unused arguments (title = "Hello", text = "This is a modal", closeOnEsc = TRUE, closeOnClickOutside = FALSE, html = FALSE, type = "success", showConfirmButton = TRUE, showCancelButton = FALSE, confirmButtonText = "OK", confirmButtonCol = "#AEDEF4", timer = 0, imageUrl = "", animation = TRUE)

Help is appreciated.

**Comment by daattali** [comment]
I'm not getting any problem with your code. Try removing all the parameters and add them back one by one to see which one gives you an error.

**Comment by syzdekbr** [comment]
Thanks, it's working now.  I changed R versions, changed back, restarted several times and getting those nice pop-ups now.  Thanks for checking.

**Comment by syzdekbr** [comment]
To follow-up, I was also using package shinysky, which masked shinyalert.

**Comment by daattali** [comment]
Sounds like  changing r versions, restarting, etc was not necessary. In the future, when reporting a bug and providing a reproducible example, always make sure to refresh your session so that the code will run  in a clean environment :)

**Comment by syzdekbr** [comment]
Indeed.  Thanks!

**Comment by nsdevoss** [comment]
> To follow-up, I was also using package shinysky, which masked shinyalert.

To anyone wondering how to fix this, format the function calls like this:
`shinyalert::shinyalert()`
