### ISSUE TITLE
Use `{priority: event}` to react at each click on the "OK" button

### ISSUE THREAD

**Issue by stla** [daattali/shinyalert#24]
Hello,

 Not sure, but maybe by replacing

`Shiny.onInputChange(cbid, value)`

with

`Shiny.setInputValue(cbid, value, {priority: event})`

then that would solve [this issue](https://stackoverflow.com/questions/60234863/reset-the-input-for-shinyalert-in-r-shiny) without needing to "reset".

**Comment by daattali** [comment]
Have you tested the github version? I think I've already implemented what you're suggesting. Please try the github version and let me know
