### ISSUE TITLE
Run in PHP (Inline)

### ISSUE THREAD

**Issue by CRO-THEHACKER** [daattali/shinyalert#25]
Hello!

I want to run this from php like:

```
<?php

echo exec("Rscript index.R");

?>
```
but, it runs as another web server? Is there an way to inline this from PHP or no?

Thanks!

PS here is a bit more:

```
Loading required package: methods
Warning message:
replacing previous import by ‘Rcpp::evalCpp’ when loading ‘later’ 

Attaching package: ‘shinyalert’

The following object is masked from ‘package:shiny’:

    runExample


Listening on http://127.0.0.1:6936
^C

Execution halted
[Fri Apr 17 21:21:12 2020] 127.0.0.1:34792 [200]: /sso/verify/index.php

```

**Comment by CRO-THEHACKER** [comment]
I really just want to run the pop up then after it has ran, it open an new PHP script  *

**Comment by daattali** [comment]
I've never seen or heard of running R from PHP. This doesn't seem like a shinyalert-specific question, it's more about the interaction of R with PHP. I don't know how that works, you'll need to ask on an online forum where people have experience with that sort of thing.
