### ISSUE TITLE
Different shinyalerts triggered at the same time

### ISSUE THREAD

**Issue by Ljupch0** [daattali/shinyalert#28]
Hi Dean, thanks for the great package.

In my app there is a situation when 2 alerts are triggered at the same time. On my machine there is no issue whatsoever, the alert that is first in the code shows first, and when it's okay-ed, the second alert shows up.

However on my colleague's machine, the first alert appears for a split second, and the second alert takes its place.

Do you have any ideas what is causing this different behavior? It's the same in different browsers on my colleague's machine.

**Comment by daattali** [comment]
Please get your colleague to submit a minimal reproducible code example,
including the version of shinyalert

**Comment by Ljupch0** [comment]
Closing for now.

**Comment by daattali** [comment]
Deep free to open an issue again if you find an issue and are able to get a reproducible example
