### ISSUE TITLE
inactive input field

### ISSUE THREAD

**Issue by sybrohee** [daattali/shinyalert#33]
Hello,

Many thanks for developing shinyalert which we really use a lot for our all bioinformatics app.

I ran into an issue :

When using a shinyalert with an input field. This input field is inactive and I cannot write in it.

When runnng the example code in my console, of course, it is working but if I include it in my code, the input field is inactivated.

The following code is running within a shinymodule and enclosed in an observeEvent (after a button pressing).

Thanks for your help,

UPDATE: Apparently, after some checks, the fact that I am running inside of a modal could be the cause of the problem.

Sylvain

```
        shinyalert(
            alertText, 
            type = "warning", 
            showCancelButton = TRUE, 
            showConfirmButton = TRUE,
            callbackR = function(value) {
                req(value)
                
                shinyalert(
                    
                    paste("Enter password for cluster user", clusterUsername),
                    type = "input", 
                    inputType = "password",                    
                    showCancelButton = TRUE, 
                    showConfirmButton = TRUE,
                    inputId = "password"
                ) 
            }
        )
```

**Comment by daattali** [comment]
As far as I know, there shouldn't be any such issues. I cannot reproduce your problem with the code you submitted. If you believe you found a bug, please create a minimal reproducible example (see [here](https://mastering-shiny.org/action-workflow.html#getting-help) for information on how to create a good minimal example)

**Comment by sybrohee** [comment]
Dear daatali, 

Thank you for your fast answer.  Please find in attachment a "working" example of my non working shinyalert. If you run it with a simple `source("path_to_file.R")`, it should be OK.

[pipelineviewerdebug.zip](https://github.com/daattali/shinyalert/files/4917465/pipelineviewerdebug.zip)

Hereafter the results of `sessionInfo()` if it can be of any help.

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_BE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_BE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_BE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyalert_1.1    data.table_1.12.2 DT_0.9            shiny_1.3.2      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2      digest_0.6.20   later_0.8.0     mime_0.7       
 [5] R6_2.4.0        xtable_1.8-4    jsonlite_1.6    magrittr_1.5   
 [9] rlang_0.4.6     promises_1.0.1  htmlwidgets_1.3 crosstalk_1.0.0
[13] yaml_2.2.0      httpuv_1.5.2    compiler_3.6.3  htmltools_0.3.6
```

**Comment by daattali** [comment]
Please send a **minimal reproducible example**. What you submitted has too much code for me to go through and does not highlight the problem in a simple way. Please see [here](https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001) or [here](https://mastering-shiny.org/action-workflow.html#getting-help) for instructions on how to create a good example when trying to get help. I will not be able to look at the issue until it's presented minimally
