### ISSUE TITLE
issue with timer when alert is followed by session$reload()

### ISSUE THREAD

**Issue by splaisan** [daattali/shinyalert#35]
what I would like is to see a message for 2sec then refresh the App to use the newly uploaded database

the code below does not wait 2sec before reloading and the user does not get the time to read the alert message
the only fix I found was to create an extra button to trigger the session reload

```
shinyalert("database uploaded", type = "success", timer=2000)
session$reload()
```

**Comment by daattali** [comment]
The timer is only a timer for when the alert should be removed automatically. The rest of the code keeps running, the tiemr isn't meant to "block" the execution of the program. This is not an issue as it's not the purpose of the timer

**Comment by daattali** [comment]
You might be able to do what you want with `shinyjs::delay` or `Sys.sleep` or maybe using the shinyalert callback parameters.
