### ISSUE TITLE
adjust size of shinyalert modal

### ISSUE THREAD

**Issue by karuno11** [daattali/shinyalert#41]
I see there is a parameter for a fixed size but if I minimize my screen, the modal size is too big and the user cannot scroll down to see all the text of the modal + the OK/Cancel buttons at the bottom. Is there a way so that the size of the modal is fluid depending on the size of the shiny app or if there's a lot of text and the user can scroll down the modal?

**Comment by daattali** [comment]
The size is in fact fluid in one way: the width of at every size will always occupy the entire page if the window is too narrow, and will only expand to the true width when the window is wide enough.

But the height doesn't have a way of knowing if it's too tall for the window. If you can find an elegant solution for that, I would be happy for a PR

**Comment by daattali** [comment]
This is the same as #44 which is now fixed
