### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by daattali** [daattali/shinyalert#54]
Extracted from #51 

Thanks for the report by @gueyenono :

> I am rendering an Rmarkdown (actually bookdown) HTML document inside shinyalert. Although the document is displayed properly inside the modal, the MathJax equations are not rendered despite the use of shiny::withMathJax().

**Comment by daattali** [comment]
You're right that MathJax doesn't seem to work. I don't know enough about how mathjax works and it's unlikely I'll fix it, unless someone else knows how to fix it. The reason I say it's unlikely I'll fix it is because I know that many other packages also struggle with mathjax, and even `shiny::insertUI()` doesn't seem to work with it:

```
library(shiny)

ui <- fluidPage(
  withMathJax(div("$$\\sqrt{1}$$")),
  actionButton("btn", "btn")
)

server <- function(input, output, session) {
  observeEvent(input$btn, {
    insertUI("body", "beforeEnd", withMathJax("$$\\sqrt{2}$$"))
  })
}

shinyApp(ui, server)
```

When I tried googling for "mathjax sweetalert" I did notice that @timelyportfolio 's sweetalertR [has a line that mentions mathjax](https://github.com/timelyportfolio/sweetalertR/blob/0e71e67793204fcd9294d37966f4f8b63041ff13/inst/examples/sweetalert_examples.Rmd#L9) so perhaps he has some information that can be helpful, but I wouldn't count on it

**Comment by daattali** [comment]
This is now supported

**Comment by gueyenono** [comment]
@daattali Is it possible to get a minimal example?

**Comment by daattali** [comment]
You can see the example used in the PR https://github.com/daattali/shinyalert/pull/57
