### ISSUE TITLE
useShinyAlert() is required with v. 2.0.0

### ISSUE THREAD

**Issue by gueyenono** [daattali/shinyalert#58]
I just installed the latest version of `shinyalert` and it seems that including `useShinyAlert()` in the UI is required again.  This is not really an issue; however, it is important to know because the examples in the Readme do not work currently.

**Comment by daattali** [comment]
Shiny apps do not need to call useShinyalert() in the ui.

If you think there's an issue with that, please post an example.

**Comment by daattali** [comment]
Oh, I think you mean the latest **CRAN version** does not support that yet. That's correct. The README on github is up to date with the github version. The documentation on the CRAN version is correct for the CRAN version. 

Closing this issue as I think it's fine for the github documentation to be up to date with its own version of the code.
