### ISSUE TITLE
Allow `inputAttributes`

### ISSUE THREAD

**Issue by stla** [daattali/shinyalert#59]
Hello,

  'SweetAlert' has an option `inputAttributes` which is not available in **shinyalert**. [Here is a use case](https://jsfiddle.net/limon/83o9p48k/). It would be nice to allow this option.

**Comment by daattali** [comment]
This package uses sweetalert 1.0.1, not version 2

The documentation for that version is at https://mcarpenterjr.github.io/sweetalert/ - it looks like `inputAttributes` is not supported in this version.

This package was created years ago and at one point I did look into upgrading to swal2, but after exploring it for a few hours I decided it was not going to work as well. Unfortunately I don't remember why I came to that conclusion. It may have been something to do with promises/callbacks and it was going to be much messier to do that in swal2. 

But as far as this issue goes - this isn't going to work unless swal2 is used.
