### ISSUE TITLE
actionbuttons

### ISSUE THREAD

**Issue by davidrsch** [daattali/shinyalert#61]
Hey, 
I want to add an action button I have added an action button in a shiny alert and when I clicked the shinyalert is closed. I want to keep showing the alert until other button is pressed. Thanks

**Comment by daattali** [comment]
Unfortunately it seems like this behaviour is due to the underlying javascript library (sweetalerts) - any `<button>` that is pressed triggers the popup to close. I'm not sure if it's possible to suppress this behaviour.
