### ISSUE TITLE
Positioning the confirm button on a shinyalert

### ISSUE THREAD

**Issue by rlmoore0** [daattali/shinyalert#62]
I'd like to re-position the confirm button in a shinyalert from the bottom of the modal to the top.  

I was clued in that the name of the element can be referenced with css styling through .alert .confirm for example, say, to change the coloring of the button.  

However, the positioning elements in css styling don't appear to work.  Any suggestions?

**Comment by daattali** [comment]
There isn't any built in way to change positioning of the buttons, that's not a feature of sweetalert.

You're right that if you want to do this it would involve adding some custom CSS rules based on the DOM. I don't know off the top of my head the exact CSS classes that exist on the HTML elements, you'd have to use a browser DOM inspector to find that out and then experiment with the CSS rules to try to see if you can move the button to the top. This is purely an HTML/CSS question, it's out of scope for shinyalert, so I'm closing.
