### ISSUE TITLE
Moving with Tab between Inputs doesn't work

### ISSUE THREAD

**Issue by malte610** [daattali/shinyalert#64]
There is bug in SweetAlert that doesn't allow to move between Inputs with the tab button. I found the following two issues, but I lack knowledge in JavaScript to implement the proposed fixes properly.

[SweetAlert Issue 127](https://github.com/t4t5/sweetalert/issues/127)
[SweetAlert Issue 391](https://github.com/t4t5/sweetalert/issues/391)

In Issue 127 it is suggested that changing "closeOnConfirm" to true solves the issue but that didn't work for me.

Reprex:

```library(shiny)
library(shinyalert)

ui <- fluidPage(
  fluidRow(
    useShinyalert(),
    actionButton("btn", "test")
  )  
)

server <- function(input, output) {
  observeEvent(input$btn, {
    shinyalert(html = TRUE,
               text = tagList(
      textInput("name", "What's your name?", "Dean"),
      numericInput("age", "How old are you?", 30),
    ))
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment]
Thanks for the report. Unfortunately, any bug present in sweetalert is going to be present here as well. It's not clear to me whether this is easily fixed and how to fix it.

**Comment by lisiarend** [comment]
This is still a problem that would be good to be considered...

**Comment by daattali** [comment]
Please see my previous reply. I cannot fix this, the developers of sweetalert knew about this bug for 8 years and haven't fixed it, I can't do it on my end.
