### ISSUE TITLE
Error with R-4.3.0

### ISSUE THREAD

**Issue by stla** [daattali/shinyalert#75]
Hello,

Previously this code in the example given in the package:

```r
shinyalert(
          html = TRUE,
          text = tagList(
            numericInput("num", "Number", 10),
            "The square of the number is",
            textOutput("square", inline = TRUE)
          )
        )
```

threw a warning: `Warning in &&: 'length = 3' in coercion to 'logical(1)'`. 

Now it throws an error. Maybe the fix is to add `any` here:

```r
if(html && any(nzchar(text)))
```

**Comment by stla** [comment]
CRAN version.

**Comment by stla** [comment]
Indeed, you already changed this code:

```r
 if (html && !is.null(params[["text"]]) && (length(params[["text"]]) > 1 || nzchar(as.character(params[["text"]]))))
```

**Comment by SebiJos** [comment]
Hi Guys, where or how to perform this change in the code?

 if (html && !is.null(params[["text"]]) && (length(params[["text"]]) > 1 || nzchar(as.character(params[["text"]]))))
==>
if(html && any(nzchar(text)))

**Comment by daattali** [comment]
It's already been done - you need to use the github version , not the CRAN version

**Comment by SebiJos** [comment]
Hi Dean,

Thanks for your answer which gives me hope I can get Shiny to work again, but I have no clue on what to do exactly? Should I reinstall RStudio from the files on Github, or only replace/update somewhere the shiny package/library?

Thanks in advance!

Seb

**Comment by stla** [comment]
@SebiJos  See `?install_github` in the **remotes** package.

**Comment by SebiJos** [comment]
> 
Hi Stla, I actually already did that, but tried again, without success.

**Comment by SebiJos** [comment]
`
R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> remotes::install_github("rstudio/shiny", force = TRUE)
Downloading GitHub repo rstudio/shiny@HEAD
-- R CMD build ----------------------------------------------------------------------------------------------------------------------------
v  checking for file 'C:\Users\josset\AppData\Local\Temp\RtmpW4rf5g\remotes8f2c171b35c7\rstudio-shiny-d21f949/DESCRIPTION' (487ms)
-  preparing 'shiny': (2.8s)
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.3s)
-  checking for empty or unneeded directories
-  building 'shiny_1.7.5.9000.tar.gz'
   
Installiere Paket nach ‘C:/Users/josset/AppData/Local/R/win-library/4.3’
(da ‘lib’ nicht spezifiziert)
* installing *source* package 'shiny' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (shiny)
Warning message:
R graphics engine version 16 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
> shiny::runApp('230828 R Files/my_shiny_app')
Lade nötiges Paket: shiny

Listening on http://127.0.0.1:5054
Warning: Error in &&: 'length = 3' in coercion to 'logical(1)'
  49: .rs.findBreakpointSteps
  48: .rs.findBreakpointSteps
  47: .rs.findBreakpointSteps
  46: .rs.findBreakpointSteps
  45: .rs.removeBreakpoints
  44: registerShinyDebugHook
  43: registerDebugHook
  42: wrapFunctionLabel
  41: .subset2(x, "impl")$defineOutput
  40: $<-.shinyoutput
  38: server [C:\Users\josset\OneDrive - Henkel\Documents\230828 R Files\my_shiny_app/app.R#38]
   1: shiny::runApp
Error in is.call(funBody[[idx]]) && as.character(funBody[[idx]][[1]]) ==  : 
  'length = 3' in coercion to 'logical(1)'`

**Comment by stla** [comment]
You want to install **shinyalert**, so do:
```
remotes::install_github("daattali/shinyalert")
```

**Comment by daattali** [comment]
A new version was submitted to CRAN today, it will be on CRAN in a few days
