### ISSUE TITLE
vertically offset fileInput 

### ISSUE THREAD

**Issue by dleopold** [daattali/shinyalert#83]
I am trying to put a fileInput() in a shinyalert modal, but the button and text input components of the file input are vertically offset. I imagine this is a simple styling fix, but I can't seem to get it right. Any ideas?

![image](https://github.com/daattali/shinyalert/assets/5009194/c4d4abac-fbba-4163-add7-dfe1dc13a23b)

```
shinyalert(
        title = "Load Plate Map",
        text = tagList(
            fileInput(ns("plateMap"), label = NULL, multiple = FALSE, accept = ".csv")
        ),
        html = TRUE,
        showCancelButton = TRUE,
        confirmButtonText = "Load",
        size = "m"
)
```

**Comment by daattali** [comment]
Thanks for solving it yourself. As you may have noticed, the sweetalert library automatically injects some CSS into `.sweet-alert input` (this isn't coming from the R package, it's coming directly from the third party javascript library).
